import { createRequestHandler } from 'react-router';
// @ts-expect-error virtual module generated by React Router
import * as build from 'virtual:react-router/server-build';
import { createApp } from './create-app';

const pageHandler = createRequestHandler(build);
let appPromise: Promise<Awaited<ReturnType<typeof createApp>>> | null = null;

export default async function handleRequest(request: Request) {
  if (!appPromise) {
    appPromise = createApp({
      handlePageRequest: (pageRequest) => pageHandler(pageRequest),
    });
  }

  const app = await appPromise;
  return app.fetch(request);
}
